export const mysqlDataTypes = [
    { label: "Varchar", value: "varchar", description: "A variable-length string" },
    { label: "Char", value: "char", description: "A fixed-length string" },
    { label: "Text", value: "text", description: "A text string" },
    { label: "Tinytext", value: "tinytext", description: "A very small text string" },
    { label: "Mediumtext", value: "mediumtext", description: "A medium-sized text string" },
    { label: "Longtext", value: "longtext", description: "A very large text string" },
    { label: "Int", value: "int", description: "A standard integer" },
    { label: "Tinyint", value: "tinyint", description: "A very small integer" },
    { label: "Smallint", value: "smallint", description: "A small integer" },
    { label: "Mediumint", value: "mediumint", description: "A medium-sized integer" },
    { label: "Bigint", value: "bigint", description: "A large integer" },
    { label: "Decimal", value: "decimal", description: "A fixed-point number" },
    { label: "Numeric", value: "numeric", description: "A numeric value" },
    { label: "Float", value: "float", description: "A floating-point number" },
    { label: "Double", value: "double", description: "A double-precision floating-point number" },
    { label: "Real", value: "real", description: "A synonym for DOUBLE" },
    { label: "Boolean", value: "boolean", description: "A true or false value" },
    { label: "Date", value: "date", description: "A date value" },
    { label: "Datetime", value: "datetime", description: "A date and time value" },
    { label: "Timestamp", value: "timestamp", description: "A timestamp value" },
    { label: "Time", value: "time", description: "A time value" },
    { label: "Year", value: "year", description: "A year value" },
    { label: "Binary", value: "binary", description: "A fixed-length binary data" },
    { label: "Varbinary", value: "varbinary", description: "A variable-length binary data" },
    { label: "Blob", value: "blob", description: "A binary large object" },
    { label: "Tinyblob", value: "tinyblob", description: "A very small binary large object" },
    { label: "Mediumblob", value: "mediumblob", description: "A medium-sized binary large object" },
    { label: "Longblob", value: "longblob", description: "A very large binary large object" },
    { label: "Enum", value: "enum", description: "An enumeration of values" },
    { label: "Set", value: "set", description: "A set of values" },
    { label: "Json", value: "json", description: "A JSON formatted value" },
    { label: "Geometry", value: "geometry", description: "A geometric object" },
    { label: "Point", value: "point", description: "A geometric point" },
    { label: "Linestring", value: "linestring", description: "A geometric line string" },
    { label: "Polygon", value: "polygon", description: "A geometric polygon" },
    { label: "Multipoint", value: "multipoint", description: "A geometric multipoint" },
    { label: "Multilinestring", value: "multilinestring", description: "A geometric multilinestring" },
    { label: "Multipolygon", value: "multipolygon", description: "A geometric multipolygon" },
    { label: "Geometrycollection", value: "geometrycollection", description: "A collection of geometric objects" }
  ];
  